apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.config | toJson | quote}}
