apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: failovermanager.plateng.vu.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: plateng.vu.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                internalURL:
                  type: string
                externalURL:
                  type: string
                pollPeriodSeconds:
                  type: int


  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: failovermanagers
    # singular name to be used as an alias on the CLI and for display
    singular: failovermanager
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: FailoverManager
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - failman
